### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by W0olFy** [karrieretutor/jitsi-prom-exporter#3]
Hello! I'm trying to compile jitsi-prom-exporter using your [README](https://github.com/karrieretutor/jitsi-prom-exporter#binary) but without any success.

go version go1.13.4 linux/amd64

Error:
```
# exporter
./main.go:150:3: cannot use promoted field TransportConfiguration.Address in struct literal of type xmpp.Config
./main.go:152:3: unknown field 'Password' in struct literal of type xmpp.Config
./main.go:155:3: cannot use promoted field TransportConfiguration.TLSConfig in struct literal of type xmpp.Config
```

**Comment by njrl** [comment]
hey,...
did you solved that problem ? having the same

**Comment by nosmicek** [comment]
see my PR, it should solve the compilation problem

**Comment by zwindler** [comment]
Hi,

I've got the same issue.

The PR doesn't solve the compilation problem either.

**Comment by icewarp** [comment]
@zwindler and what is the problem? just stating "i have a problem" doesn't help me to get any idea what is wrong at all.. 

so please, can u be more specific, can u at least paste the compilation error here? with steps u did, e.g. i cloned with this command, than i applied your patch with this command, then i invoked maven with this command and here is the error i got.. 
i can't help u with no information.. i did compile sucessfully yesterday with no modification to my patch, and guessing other people's problems is not my area of expertise ;)
p.s.: i'm not developer nor somehow related to active development of this exporter, i'm just using it and found a way how to go around some obstacles so i want to share them, because i think it might be usefull for others

**Comment by icewarp** [comment]
so my commands (in general):
```
git clone https://github.com/karrieretutor/jitsi-prom-exporter.git
cd jitsi-prom-exporter
git remote add nosmicek https://github.com/nosmicek/jitsi-prom-exporter
git fetch nosmicek
git checkout -b patchx nosmicek/patch-1
git checkout master
git merge patchx
docker build . -t jitsi-prometheus-exporter:latest
```
voilá, docker image build..

**Comment by zwindler** [comment]
@icewarp I understand. If I write "I've got the same issue" it means "I've got the same issue".

I fail to see how copy pasting the EXACT same error message than the initial poster will help in any way, but fair, I'll post it.

**Comment by nosmicek** [comment]
@zwindler and did u apply the aforementioned patch (see pull request, #5 ) and compiled modified code than?

**Comment by zwindler** [comment]
As requested, my procedure (including steps not given in the README.md that I had to find out by myself)

Find the jisti-meet-cfg.lua

```bash
locate cfg.lua
/etc/prosody/conf.d/your.domain.tld.cfg.lua
```
Guess the "auth-domain", in my example I think this is auth.your.domain.tld. Laucnh the prosodyctl command given in the README.md

```bash
prosodyctl --config /etc/prosody/conf.d/your.domain.tld.cfg.lua register exporter auth.your.domain.tld myawesomepassword
```

Install prerequisites (nothing mentionned in the README.md)

```bash
sudo apt update
sudo apt install software-properties-common

sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt update
sudo apt install golang-go git
```

Get and compile the sources. Again, some guessing to do, as this step is only describe as "Clone this repo into your $GOPATH/src/ directory. In the exporter directroy run go get ./... which creates the exporter binary in $GOPTAH/bin/."

```bash
su - jvb
mkdir -p go/src && mkdir -p go/bin
cd go/src
git clone https://github.com/karrieretutor/jitsi-prom-exporter
cd jitsi-prom-exporter/
go get ./...
```

The error
```bash
# jitsi-prom-exporter.ori/exporter
exporter/main.go:150:3: cannot use promoted field TransportConfiguration.Address in struct literal of type xmpp.Config
exporter/main.go:152:3: unknown field 'Password' in struct literal of type xmpp.Config
exporter/main.go:155:3: cannot use promoted field TransportConfiguration.TLSConfig in struct literal of type xmpp.Config
exporter/main.go:264:31: not enough arguments in call to xmpp.NewClient
	have (xmpp.Config, *xmpp.Router)
	want (*xmpp.Config, *xmpp.Router, func(error))
```

**Comment by zwindler** [comment]
@nosmicek my bad. I thought I had tried your PR but I wasn't in fact in the good branch (in master, not patch-1 from the PR)...

```bash
git clone https://github.com/nosmicek/jitsi-prom-exporter.git
cd jitsi-prom-exporter
git checkout patch-1
git branch
  master
* patch-1
go get ./...
```

So it seems to compile with the PR. Sorry for saying otherwise. Now I have to find out how to run it

**Comment by raj2569** [comment]
git fetch origin pull/5/head:pr-5
    go get ./...

and successfully compiled. go version go1.14.2 linux/amd64

**Comment by zwindler** [comment]
OK... so after doing some digging and a lot of trial and error I finally managed to run it... 

The binary doesn't have any help nor flags so you have to configure ALL the environment variables cited in the doc. And the PR changes some of those so I lost a little time there as well.

In order to avoid anyone to lose time like I did, the correct procedure, in addition to my previous commands (to compile it)

```bash
cd go/bin
export PROMEXP_AUTH_USER=exporter
export PROMEXP_AUTH_PASSWORD=myawesomepassword
export XMPP_SERVER=127.0.0.1
export XMPP_AUTH_DOMAIN=auth.jitsi.domain.tld
export XMPP_INTERNAL_MUC_DOMAIN=internal.auth.jitsi.domain.tld
export JVB_BREWERY_MUC=JvbBrewery
./exporter
```

**exporter** and **myawesomepassword** being the login/password previously set with `prosodyctl`.

**XMPP_SERVER** is the address the XMPP server is listening on. 127.0.0.1 is a pretty safe bet but check with `ss`.

As I said previously, **XMPP_AUTH_DOMAIN** can be found in `/etc/prosody/conf.d/your.domain.tld.cfg.lua`

And for **XMPP_INTERNAL_MUC_DOMAIN** and **JVB_BREWERY_MUC**, they can be found in `/etc/jitsi/videobridge/sip-communicator.properties`

Fun fact, I haven't found a way to specify which port the exporter listens to, making it by default listening to the 8080 port which is incompatible with my own setup.

I'm using another exporter (jitsiexporter) now.

**Comment by nosmicek** [comment]
@zwindler so you are basically saying, that u didn't read any documentation, tried by trial and error, than finaly read the documentation and made it work.. well, congratulations! :D 
i'm curious because it seems that u don't have any idea about jitsi and its configuration (this exporter uses all the standard jitsi configuration variables and jitsi way how to do the configuration), how did u came here? i don't mean to be rude, but well.. being surprised by basic things..

**Comment by zwindler** [comment]
I don't mean to be rude either, but I'm always amazed about how people
neglect documentation.

What I did IS documentation. Explaining what has to be done AND why, step
by step. That's not what is in the README. Having a binairy without --help
nor parameters doesn't help. That's pretty Basic development tips, and I'm
not even a developer.

As for not having any idea about how Jitsi work (or golang for that
matter), I guess we see the world differently. You seem to think that you
have to know everything about a software to use it. I think this is
ridiculous. What's really elitist and Goes against the free software and
open source philosophies in my opinion.

I don't know Jitsi standard variables because I don't need to. There are
configuration files, which is a way efficient way to configure software.

I regret Being bitter in my previous message, but I did loose a lot of
time, which could have been easily avoided should anyone had taken the time
to write proper documentation, proper help and didn't introduce breaking
changes without telling.

Regards

**Comment by msalmasi** [comment]
@nosmicek Thanks for the fix, you are awesome!

@zwindler Thanks for letting us know how you got it working, you are the documentation now XD

**Comment by nosmicek** [comment]
@msalmasi u r welcome.. 

for the rest of ppl, so as not to be mistaken like @zwindler.. 

this piece of software is mainly meant to run in docker, that goes for the configuration via env variables.. it's not specifically written anywhere, but when there is ONLY one paragraph stating DOCKER container, and then configuration, i thought (and author probably too), that it is enough to hint you of meant usage.
Yes, port is hardcoded and it is mentioned in documentation, but that is just one line in file, you can easily change it, no special skill needed..
Yes, **my patch makes changes to some env vars**, so please read documentation after merging, or commit messages that state all made changes. My patch also clears some of the configuration setup burden, you can avoid some trial&error rounds ;)

@zwindler ok, we have different view on this, you are not developer, so please don't expect real developers to act like u wish, good luck
(end of flame war, if u want to continue this philosophical debate, then via email or other means, not via github)
